name: Build on Push
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: (Hacky) method of compiling Geyser with Floodgate first
        run: |
          git clone https://github.com/Tim203/Geyser.git GeyserFloodgate
          cd GeyserFloodgate
          mvn clean install
          cd ..
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build with Maven
        run: mvn clean package
      - name: Archive artifacts (Bukkit)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Bukkit Floodgate
          path: bukkit/target/floodgate-bukkit.jar
      - name: Archive artifacts (Bungee)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Bungee Floodgate
          path: bungee/target/floodgate-bungee.jar
